# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # Daily updates for npm package versions
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    labels:
      - 'version-update'
  - package-ecosystem: 'npm' # Daily security-updates only for npm versions on the release branch
    directory: '/'
    target-branch: 'release'
    schedule:
      interval: 'daily'
    labels:
      - 'security-update'
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      security-dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        applies-to: version-updates # Applies the group rule to version updates
        patterns:
          - '*'
